sudo: required
dist: trusty
language: node_js
node_js:
  - '6.9'

services:
  - docker

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - docker build -t project-hub .
  - docker run -d -p 4200:4200 --name project-hub project-hub

before_script:
- npm install -g angular-cli
- npm install -g karma
- npm install
- ng build

script: karma start karma.conf.js --single-run